swagger: "2.0"
info:
  version: '1.0'
  title: General Api
  description: 'Contract for the application'

host: localhost:8082

paths:
  /getlistofbookbyuser/{userId}:
    get:
      tags:
        - bookHistory
      summary: get list of books for specific user
      description: purpose of this function is to get a list books attached to a specific user
      operationId: getBooksByUser
      produces:
        - application/json
      parameters:
        - in: path
          name: userId
          type: integer
          format: int64
          description: the id of the user object
          required: true
      responses:
        200:
          description: returns a list of books binds to a specific user
          schema:
            type: array
            items:
              $ref: '#/definitions/Book'

  /hidebookbyuser:
    post:
      tags:
        - bookHistory
      summary: hide a specific book
      description: purpose of this function is to hide a specific book for a user
      operationId: hideBookByUser
      produces:
        - application/json
      parameters:
        - in: body
          name: bookHistory
          description: name of the bookhistory object to hide
          schema:
            $ref: '#/definitions/HideBookHistoryRequestGW'
      responses:
        200:
          description: status code along with the specific book object
          schema:
            $ref: '#/definitions/HideBookHistoryResponseGW'
definitions:
  HideBookHistoryRequestGW:
    type: object
    description: Request object for a user to hide a specific book
    properties:
      userId:
        type: integer
        format: int64
      bookId:
        type: integer
        format: int64
      location:
        type: string
      description:
        type: string
      bookStatus:
        type: string
        enum:
          - owned
          - hidden
  HideBookHistoryResponseGW:
    type: object
    description: Response object for a user
    properties:
      userId:
        type: integer
        format: int64
      bookId:
        type: integer
        format: int64
      location:
        type: string
      description:
        type: string
  Book:
    type: object
    description: This Book object defined below is used for the transactions in the app
    properties:
      id:
        type: integer
        format: int64
      author:
        type: string
      title:
        type: string
      genre:
        type: string
      numberOfPages:
        type: integer
      language:
        type: string

